services:

  postgres:
    image: postgres:17
    container_name: cerebro_postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: cerebro_digital
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123

    ports:
      - "5432:5432"

    volumes:
      - ./postgres_data:/var/lib/postgresql/data

    networks:
      - cerebro_network


  pgadmin:
    image: dpage/pgadmin4

    container_name: cerebro_pgadmin

    restart: unless-stopped

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@cerebro.com
      PGADMIN_DEFAULT_PASSWORD: admin123

    ports:
      - "5050:80"

    depends_on:
      - postgres

    networks:
      - cerebro_network


  redis:
    image: redis:8

    container_name: cerebro_redis

    restart: unless-stopped

    ports:
      - "6379:6379"

    volumes:
      - ./redis_data:/data

    networks:
      - cerebro_network


networks:
  cerebro_network:
    external: true